### ISSUE TITLE
Rewardpage (parent)

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#10]
Giving our rewardpage something to work with

### Value Proposition

As a user i want to see and create my rewards

### Description

<img width="901" alt="Screenshot 2022-12-04 at 18 17 11" src="https://user-images.githubusercontent.com/113447663/205505429-e3426bb8-203b-4046-a92f-ce13fdd0334d.png">

### Acceptance Criteria

- [ ] the rewardpage should render dummyrewards 
- [ ] when logged in as a parent, there should be an "add" button to create new rewards
- [ ] the title and costs are necessary to define. a picture can be chosen and a preview will appear, although it does not get saved (yet). on the rewardpage a placeholder image will be shown.

### Tasks

(for developers team)

- [ ] create a new databank for rewards
- [ ] add dummyrewards
- [ ] add a grid for reward elements
- [ ] link the add-button to a new page
- [ ] the new page contains a form with inputs for title and rewards. also a button to add a picture + preview

### Sizing/Complexity

**M**

**Comment by marcos-de-barros-vioque** [comment]
Well done, Max!
