### ISSUE TITLE
finishing tasks (child)

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#14]
lets give our children the ability to finish tasks

### Value Proposition

As a user i want to finish tasks to be able to gain rewards for it

### Description

![Screenshot 2022-12-12 at 11 13 02](https://user-images.githubusercontent.com/113447663/207019691-41527720-2b32-4c87-9912-157c9bf422c7.png)

### Acceptance Criteria

- [ ] when logged in as a child, you see a "done" button
- [ ] when clicking on that button, you get a popup which asks you if you are sure to finish the task
- [ ] after confirming the task will disappear from the list and you get a message, that it will be reviewed by the parent
- [ ] when logged in as parent you can confirm the completed task

### Tasks

(for developers team)

- [ ] add a check button linked to "child" state
- [ ] add a popup for the button
- [ ] add "review" key for tasks
- [ ] update the value for "review" to "in review" when clicked on "confirm"
- [ ] filter out "in review" tasks (homepage, children)
- [ ] (parent) filter tasks, with "in review" tasks shown at the top of the page
- [ ] add a "confirm" button to update the "in review" value to "reviewed"

### Sizing/Complexity

**M**
