### ISSUE TITLE
adding more children

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#15]
loginpage update with the ability to add children

### Value Proposition

As a parent i want to add more children and save their data in a database

### Description

![Screenshot 2022-12-12 at 12 40 36](https://user-images.githubusercontent.com/113447663/207036659-39587241-dee1-4b49-9ddf-2171dd6782d1.png)

### Acceptance Criteria

- [ ] when logged in as a parent, you see an "add child" button on the loginpage
- [ ] after clicking on the button a popup window will appear, asking you what the name of your child is
- [ ] after adding a child, a new profile will appear on the loginpage

### Tasks

(for developers team)

- [ ] "add" button linked to parent state
- [ ] create new database for children
- [ ] update the database with adding a child
- [ ] render children profiles on the loginpage based of the database entries

### Sizing/Complexity

**M**

**Comment by stefankorder** [comment]
Hi Max,
do you wanna save the children inside a database as a user? I think your value proposition should be written in a different way.

**Comment by MaxMer25** [comment]
@stefankorder thanks for pointing that out, i changed it!
