### ISSUE TITLE
displaying current Userdata (child)

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#16]
first steps to an "rpg" app

### Value Proposition

As a child i want to see my current gold, level and experience on my homepage

### Description

![Screenshot 2022-12-12 at 12 01 14](https://user-images.githubusercontent.com/113447663/207029322-bc67dc4a-7525-4ef2-a1db-e4ea623e9ac9.png)

### Acceptance Criteria

- [x] when logged in as a child and on the homepage, you see a level bar at the top of the page and your gold at the bottom
- [x] the values from both of these components are related to your completed tasks
- [x] next to the levelbar is a levelindicator, showing your current level
- [x] next to the levelindicator is an avatar. avatars correlate with level. higher level -> cooler avatar

### Tasks

(for developers team)

- [ ] create a progress bar, level, avatar and goldwallet
- [ ] gold will show sum of child-database-gold entries
- [ ] come up with a formula, to make leveling harder with each level
- [ ] style everything with "rpg" elements
- [ ] find some cool avatars
- [ ] avatar will be changed based on level

### Sizing/Complexity

**L**
