### ISSUE TITLE
Profilepage

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#19]
Creating a dynamic profilepage for the children

### Value Proposition

As a child i would like to have a profile page, where i have a general overview about my current leveling process and ressources

### Description

![Screenshot 2022-12-16 at 10 08 51](https://user-images.githubusercontent.com/113447663/208064105-77bf6f6d-d74b-4672-9b6c-c6ef7ad8aa6f.png)

### Acceptance Criteria

- [ ] after logging in with a childaccount, you will get redirected to your profile page
- [ ] to switch profiles or sign out in general, there shall be a "sign out" button
- [ ] on the profile page you will see your avatar (based on your level), your experience progressbar and your gold

### Tasks

(for developers team)

- [ ] set a route for every mapped children profile to the profile page
- [ ] change the navbar according to user.type = Child
- [ ] on the profilepage, fetch the userdata and render the rpg-elements

### Sizing/Complexity

**M**
