### ISSUE TITLE
App first Layout with navigation bar

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#2]
### Value Proposition

As a User
i need a navigation that gets me to different pages and a first login page to see

### Description

![Image](https://user-images.githubusercontent.com/113447663/204521031-47405e8a-249c-4247-946e-d64a146b39b1.png)
login page with dummy Icons

![Screenshot 2022-11-28 at 10 13 53](https://user-images.githubusercontent.com/113447663/204239281-010ec45a-a3a9-4a8b-8fcd-056a0c6f3e29.png)

### Acceptance Criteria

- [x] the first page, login, should be created
- [x] the login page has 2 Icons. One for parent, one for child
- [x] the app has a navigation bar
- [x] within the navigation bar there are 3 navelements (login, home, reward)
- [x] the navelements should already link to a different page with a "work in progress" text 
- [x] when a navigation button is active, it should be highlighted
### Tasks

(for developers team)

- [x] Create 3 Pages
- [x] Add two dummy Icons for login purpose
- [x] Create navigation bar with the elements
- [x] The Home and Reward Page should display a "work in progress" text
### Sizing/Complexity

**S**
