### ISSUE TITLE
Buying rewards

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#20]
Our kids have done their work, now lets reward them!

### Value Proposition

As a Child i want to buy rewards on the rewardpage so i can spend my hard earned cubCoins

### Description

![Screenshot 2022-12-16 at 11 09 13](https://user-images.githubusercontent.com/113447663/208076073-ae2a765d-0197-4df3-9197-ac3089c2a736.png)

### Acceptance Criteria

- [ ] when logged in as a Child, you will see the rewards on the rewardpage with a shopping symbol that lets you purchase an item from the shop
- [ ] after clicking on the shopping cart symbol, you will see a menu where you can chose how many times you wish to purchase the item

**Unsuccessful purchase**
- [ ] if you don't have enough gold to buy all selected items, you will get an error message telling you you don't have enough gold

**Successful purchase**
- [ ] if you have enough gold you will get a success-popup, telling you that the purchase was successful. In addition the popup will render your updated goldamount

### Tasks

(for developers team)

- [ ] add "buy" button
- [ ] check gold with buy button
- [ ] add error messages
- [ ] add success popup
- [ ] add reward to user database

### Sizing/Complexity

**L**
