### ISSUE TITLE
login data stored in local storage

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#3]
### Value Proposition

As a user
i wanna be able to login and want my usertype (child or parent) saved
so my app can adapt to each type

### Description

![Screenshot 2022-11-28 at 12 56 16](https://user-images.githubusercontent.com/113447663/204271903-5c85f5ba-5d3f-4ee1-95e1-aba169602364.png)

### Acceptance Criteria

- [x] the login page should display two login buttons with images indicating if a child or parent wants to log in
- [x] after clicking on either one of them, you get an alert which welcomes your usertype

### Tasks

(for developers team)

- [x] add a "choose usertype" headline
- [x] add two clickable icons
- [x] depending on which icon is clicked (parent or child) the corresponding value should be stored in the local storage
- [x] after that an alert pops up with a greeting message containing the usertype

### Sizing/Complexity

**M**
