### ISSUE TITLE
Homepage Tasks

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#7]
Rendering first dummy Tasks on the Homepage

### Value Proposition

As a user i need my Tasks displayed on the homepage

### Description

![Screenshot 2022-12-01 at 10 56 52](https://user-images.githubusercontent.com/113447663/205023085-09d2b767-e57a-434a-a292-e771e4d2f7ef.png)

### Acceptance Criteria

- [ ] When the user is on the Homepage, the app should render placeholder tasks
- [ ] the "details" button should redirect to another path "/details" which shows a "work in progress text"
 
### Tasks

(for developers team)

- [ ] set up a mongoDB and the corresponding api
- [ ] create dummy tasks for demo purpose
- [ ] give the tasks a basic style to work with
- [ ] add a "details" button

### Sizing/Complexity

**L**
