### ISSUE TITLE
Adding Tasks

### ISSUE THREAD

**Issue by MaxMer25** [MaxMer25/Capstone---lvlCub#9]
### Value Proposition

As a user i need an "add" button on the homepage to create new tasks for my children.

### Description

Scribble / design or text

<img width="1209" alt="Screenshot 2022-12-04 at 17 48 27" src="https://user-images.githubusercontent.com/113447663/205504125-b87c2bdf-d6f1-48b6-b8e0-691c0da309dd.png">

- [ ] when you are logged in as a parent, you should see an "add" button on the homepage
- [ ] by clicking on the button you will get redirected to another page, where you can create a new task
- [ ] the task will require a title and rewards. the description, picture, date and child-specificity-menu are optional
- [ ] the form should contain a submit button to save your task

### Tasks

(for developers team)

- [ ] create a standard "add" button to work with (also for the future)
- [ ] link a new route to that button
- [ ] create the form for the user to create a new task
- [ ] the form contains input fields for the title, description and rewards, a calendar-type input, a button to upload a picture, the preview of the picture and a menu to specify the task for a child

### Sizing/Complexity

**M**
